### ISSUE TITLE
JSX support for transform() API method 

### ISSUE THREAD

**Issue by arm1n** [wessberg/DI-compiler#24]
I am trying to use the [proposed approach from the docs](https://github.com/wessberg/DI-compiler#usage-as-an-api) with direct usage of `transform(code, filename, options)`.

Unfortunately, this does not work when running TSX files as `transform()` is [hardcoding the script type](https://github.com/wessberg/DI-compiler/blob/master/src/transformer/transform.ts#L43) to `ScriptKind.TS`.

From a quick test it would be sufficient to simply remove this parameter, TS seems to figure it out implicitly. Alternatively, using a factory method [like used in the tests](https://github.com/wessberg/DI-compiler/blob/master/test/setup/setup-custom-transformer.ts#L126) would be possible as well I guess.

Is there any chance to get TSX for the `transform()` method? It would be super helpful as it's a tremendous performance improvement compared to using the rollup TS plugin.

Thanks for any response and the awesome work on this piece of code!

**Comment by wessberg** [comment]
Hey there. Thanks for your contribution. It has been merged in and will be part of the next major release.
